language: php

php:
  - 5.6.4
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
